name   名字: 'publish'   “发布”

on   在:
  push   推:
    branches   分支机构:
      - release

# This workflow will trigger on each push to the `release` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.这个工作流将在每次推送到“发布”分支时触发，以创建或更新GitHub发布，构建应用程序，并将工件上传到发布。

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false   假
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'   “windows-latest”
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name   名字: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name   名字: install Rust stable
        uses: dtolnay/rust-toolchain@stable用途：DTOLNAY/Rust-toolchain@stable
        with:   :
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.#这些目标只在macos运行器上使用，所以它在if中是为了稍微加快windows和linux的构建速度。
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}目标:${{矩阵。平台== 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || "}}

      - name: install dependencies (ubuntu only)- name:安装依赖项(仅限ubuntu)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.如果:矩阵。platform == 'ubuntu-22.04' #必须匹配上面定义的平台值。
        run: |   运行:|
          sudo apt-get update   Sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelflibwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev libsvg2 -dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.# webkitgtk 4.0适用于金牛v1 - webkitgtk 4.1适用于金牛v2。
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.你可以删除一个不适用于你的应用程序，以加快工作流程。

      - name: install frontend dependencies—name:安装前端依赖项
        run: yarn install # change this to npm, pnpm or bun depending on which one you use.运行命令:yarn install #将其改为npm, PNPM或bun，具体取决于你使用的是哪个。

      - uses: tauri-apps/tauri-action@v0- 用途：tauri-apps/tauri-action@v0
        env:   环境：
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}GITHUB_TOKEN: ${{秘密。GITHUB_TOKEN}}
        with:   :
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.tagName: app- v__version__ #该操作自动将\_\_VERSION\_\_替换为应用程序版本。
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'releaseBody: '查看下载并安装此版本的资源。'
          releaseDraft: true   releaseDraft:真
          prerelease: false   预映:假
          args: ${{ matrix.args }}
